### ISSUE TITLE
problem of the code

### ISSUE THREAD

**Issue by DingkunLong** [jostmey/rwa#6]
As a biginner of tensorflow, I have meet some problem with your code.
by "python train.py",I get raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/abc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

___________________________________________
Using adding problem as example, when define the model:
x_step = [:i:] be shape(1, max_steps, num_classes), h be shape(bach_size, num_cells),
can we do tf.concat with these two components?

**Comment by jostmey** [comment]
What example is this? Is it the RWA or the LSTM code?  Also, the code is written to run in Python3, That said, I suspect the code should also work in Python2.

**Comment by DingkunLong** [comment]
adding proeblem-100, the RWA and LSTM model both face the problem

**Comment by jostmey** [comment]
I am unable to recreate the bug. Are you using the latest version of TensorFlow?

Thanks

**Comment by DingkunLong** [comment]
yes, I'm using the latest version tensorflow-1.0
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import dataplumbing as dp
  File "/home/abc/exp/RWA/rwa-master/adding_problem_100/rwa_model/dataplumbing.py", line 42, in <module>
    import input_data
  File "../dataset/input_data.py", line 34, in <module>
    os.makedirs(_path+'/bin', exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
here is the error. anyway, thanks a lot for your help

**Comment by jostmey** [comment]
Okay, that bug is from using python2 instead of python3. If you really want to use python2, you will need to edit the code. Go to "adding-problem-100/dataset" and edit "input_data.py". Comment out the line "os.makedirs(_path+'/bin', exist_ok=True)". Since you have removed this line of code, you will need to manually create the folder each time. So if you use linux, create a folder "adding-problem-100/dataset/bin" before running the code. This should work for most examples

**Comment by Hima-Mehta** [comment]
There are few issues to be solved with Tf 1.0 which can be verified from [Release.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) 
For example :

> 1)  Replace tf.select by tf.where.    
>2)  Replace tf.tf.concat(1, [x_step, h]) by tf.concat([x_step, h],1).    
>3) Replace tf.mul, tf.sub and tf.neg with tf.multiply, tf.subtract and tf.negative.    
>4) Replace tf.nn.sigmoid_cross_entropy_with_logits(ly_flat,y) with tf.nn.sigmoid_cross_entropy_with_logits(logits=ly_flat,labels=y).    
Etc.

**Comment by Hima-Mehta** [comment]
I have Made above changes in adding_problem_100 and It works perfectly fine !

**Comment by jostmey** [comment]
Thanks for letting me know it worked! I'm closing this issue
